export const countryMap: { [key: string]: string } = {
  "ms-BN": "kxd",
  "ms-MY": "ms",
  "ms-SP": "mssg",
  "ms-SG": "mssg",
};

export const languageMap: { [key: string]: string } = {
  ab: "аҧсуа бызшәа",
  abk: "аҧсуа бызшәа",
  aa: "Afaraf",
  aar: "Afaraf",
  af: "Afrikaans",
  afr: "Afrikaans",
  ak: "Akan",
  aka: "Akan",
  fat: "Akan",
  sq: "Shqip",
  sqi: "Shqip",
  alb: "Shqip",
  aae: "Shqip",
  aat: "Shqip",
  aln: "Shqip",
  als: "Shqip",
  am: "አማርኛ",
  amh: "አማርኛ",
  ar: "العربية",
  ara: "العربية",
  aao: "العربية",
  abh: "العربية",
  abv: "العربية",
  acm: "العربية",
  acq: "العربية",
  acw: "العربية",
  acx: "العربية",
  acy: "العربية",
  adf: "العربية",
  aeb: "العربية",
  aec: "العربية",
  afb: "العربية",
  ajp: "العربية",
  apc: "العربية",
  apd: "العربية",
  arb: "العربية",
  arq: "العربية",
  ars: "العربية",
  ary: "العربية",
  arz: "العربية",
  auz: "العربية",
  avl: "العربية",
  ayh: "العربية",
  ayl: "العربية",
  ayn: "العربية",
  ayp: "العربية",
  bbz: "العربية",
  pga: "العربية",
  shu: "العربية",
  ssh: "العربية",
  an: "aragonés",
  arg: "aragonés",
  hy: "Հայերեն",
  hye: "Հայերեն",
  arm: "Հայերեն",
  as: "অসমীয়া",
  asm: "অসমীয়া",
  av: "авар мацӀ",
  ava: "авар мацӀ",
  ae: "avesta",
  ave: "avesta",
  ay: "aymar aru",
  aym: "aymar aru",
  ayr: "aymar aru",
  ayc: "aymar aru",
  az: "Azərbaycan dili",
  aze: "Azərbaycan dili",
  azj: "Azərbaycan dili",
  azb: "Azərbaycan dili",
  bm: "bamanankan",
  bam: "bamanankan",
  ba: "башҡорт теле",
  bak: "башҡорт теле",
  eu: "euskara",
  eus: "euskara",
  baq: "euskara",
  be: "беларуская мова",
  bel: "беларуская мова",
  bn: "বাংলা",
  ben: "বাংলা",
  bh: "भोजपुरी",
  bih: "भोजपुरी",
  bi: "Bislama",
  bis: "Bislama",
  bs: "bosanski jezik",
  bos: "bosanski jezik",
  br: "brezhoneg",
  bre: "brezhoneg",
  bg: "български език",
  bul: "български език",
  my: "ဗမာစာ",
  mya: "ဗမာစာ",
  bur: "ဗမာစာ",
  ca: "català",
  cat: "català",
  ch: "Chamoru",
  cha: "Chamoru",
  ce: "нохчийн мотт",
  che: "нохчийн мотт",
  ny: "chiCheŵa",
  nya: "chiCheŵa",
  zh: "中文",
  zho: "中文",
  chi: "中文",
  cdo: "中文",
  cjy: "中文",
  cmn: "中文",
  cpx: "中文",
  czh: "中文",
  czo: "中文",
  gan: "中文",
  hak: "中文",
  hsn: "中文",
  lzh: "中文",
  mnp: "中文",
  nan: "中文",
  wuu: "中文",
  yue: "中文",
  cv: "чӑваш чӗлхи",
  chv: "чӑваш чӗлхи",
  kw: "Kernewek",
  cor: "Kernewek",
  co: "corsu",
  cos: "corsu",
  cr: "ᓀᐦᐃᔭᐍᐏᐣ",
  cre: "ᓀᐦᐃᔭᐍᐏᐣ",
  crm: "ᓀᐦᐃᔭᐍᐏᐣ",
  crl: "ᓀᐦᐃᔭᐍᐏᐣ",
  crk: "ᓀᐦᐃᔭᐍᐏᐣ",
  crj: "ᓀᐦᐃᔭᐍᐏᐣ",
  csw: "ᓀᐦᐃᔭᐍᐏᐣ",
  cwd: "ᓀᐦᐃᔭᐍᐏᐣ",
  hr: "hrvatski jezik",
  hrv: "hrvatski jezik",
  cs: "čeština",
  ces: "čeština",
  cze: "čeština",
  da: "dansk",
  dan: "dansk",
  dv: "ދިވެހި",
  div: "ދިވެހި",
  nl: "Nederlands",
  nld: "Nederlands",
  dut: "Nederlands",
  dz: "རྫོང་ཁ",
  dzo: "རྫོང་ཁ",
  en: "English",
  eng: "English",
  eo: "Esperanto",
  epo: "Esperanto",
  et: "eesti",
  est: "eesti",
  ekk: "eesti",
  vro: "eesti",
  ee: "Eʋegbe",
  ewe: "Eʋegbe",
  fo: "føroyskt",
  fao: "føroyskt",
  fj: "vosa Vakaviti",
  fij: "vosa Vakaviti",
  fi: "suomi",
  fin: "suomi",
  fr: "français",
  fra: "français",
  fre: "français",
  ff: "Fulfulde",
  ful: "Fulfulde",
  fub: "Fulfulde",
  fui: "Fulfulde",
  fue: "Fulfulde",
  fuq: "Fulfulde",
  ffm: "Fulfulde",
  fuv: "Fulfulde",
  fuc: "Fulfulde",
  fuf: "Fulfulde",
  fuh: "Fulfulde",
  gl: "Galego",
  glg: "Galego",
  ka: "ქართული",
  kat: "ქართული",
  geo: "ქართული",
  de: "Deutsch",
  deu: "Deutsch",
  ger: "Deutsch",
  el: "ελληνικά",
  ell: "ελληνικά",
  gre: "ελληνικά",
  gn: "Avañe'ẽ",
  grn: "Avañe'ẽ",
  nhd: "Avañe'ẽ",
  gui: "Avañe'ẽ",
  gun: "Avañe'ẽ",
  gug: "Avañe'ẽ",
  gnw: "Avañe'ẽ",
  gu: "ગુજરાતી",
  guj: "ગુજરાતી",
  ht: "Kreyòl ayisyen",
  hat: "Kreyòl ayisyen",
  ha: "هَوُسَ",
  hau: "هَوُسَ",
  he: "עברית",
  heb: "עברית",
  hz: "Otjiherero",
  her: "Otjiherero",
  hi: "हिन्दी",
  hin: "हिन्दी",
  ho: "Hiri Motu",
  hmo: "Hiri Motu",
  hu: "magyar",
  hun: "magyar",
  ia: "Interlingua",
  ina: "Interlingua",
  id: "Bahasa Indonesia",
  ind: "Bahasa Indonesia",
  ie: "Occidental",
  ile: "Occidental",
  ga: "Gaeilge",
  gle: "Gaeilge",
  ig: "Asụsụ Igbo",
  ibo: "Asụsụ Igbo",
  ik: "Iñupiaq",
  ipk: "Iñupiaq",
  esi: "Iñupiaq",
  esk: "Iñupiaq",
  io: "Ido",
  ido: "Ido",
  is: "Íslenska",
  isl: "Íslenska",
  ice: "Íslenska",
  it: "Italiano",
  ita: "Italiano",
  iu: "ᐃᓄᒃᑎᑐᑦ",
  iku: "ᐃᓄᒃᑎᑐᑦ",
  ike: "ᐃᓄᒃᑎᑐᑦ",
  ikt: "ᐃᓄᒃᑎᑐᑦ",
  ja: "日本語",
  jpn: "日本語",
  jv: "ꦧꦱꦗꦮ",
  jav: "ꦧꦱꦗꦮ",
  kl: "kalaallisut",
  kal: "kalaallisut",
  kn: "ಕನ್ನಡ",
  kan: "ಕನ್ನಡ",
  kr: "Kanuri",
  kau: "Kanuri",
  knc: "Kanuri",
  kby: "Kanuri",
  krt: "Kanuri",
  ks: "कश्मीरी",
  kas: "कश्मीरी",
  kk: "қазақ тілі",
  kaz: "қазақ тілі",
  km: "ខ្មែរ",
  khm: "ខ្មែរ",
  ki: "Gĩkũyũ",
  kik: "Gĩkũyũ",
  rw: "Ikinyarwanda",
  kin: "Ikinyarwanda",
  ky: "Кыргызча",
  kir: "Кыргызча",
  kv: "коми кыв",
  kom: "коми кыв",
  koi: "коми кыв",
  kpv: "коми кыв",
  kg: "Kikongo",
  kon: "Kikongo",
  kng: "Kikongo",
  ldi: "Kikongo",
  kwy: "Kikongo",
  ko: "한국어",
  kor: "한국어",
  ku: "Kurdî",
  kur: "Kurdî",
  ckb: "Kurdî",
  kmr: "Kurdî",
  sdh: "Kurdî",
  kj: "Kuanyama",
  kua: "Kuanyama",
  la: "latine",
  lat: "latine",
  lb: "Lëtzebuergesch",
  ltz: "Lëtzebuergesch",
  lg: "Luganda",
  lug: "Luganda",
  li: "Limburgs",
  lim: "Limburgs",
  ln: "Lingála",
  lin: "Lingála",
  lo: "ພາສາລາວ",
  lao: "ພາສາລາວ",
  lt: "lietuvių kalba",
  lit: "lietuvių kalba",
  lu: "Kiluba",
  lub: "Kiluba",
  lv: "latviešu valoda",
  lav: "latviešu valoda",
  ltg: "latviešu valoda",
  lvs: "latviešu valoda",
  gv: "Gaelg",
  glv: "Gaelg",
  mk: "македонски јазик",
  mkd: "македонски јазик",
  mac: "македонски јазик",
  mg: "fiteny malagasy",
  mlg: "fiteny malagasy",
  xmv: "fiteny malagasy",
  bhr: "fiteny malagasy",
  msh: "fiteny malagasy",
  bmm: "fiteny malagasy",
  plt: "fiteny malagasy",
  skg: "fiteny malagasy",
  bzc: "fiteny malagasy",
  tkg: "fiteny malagasy",
  tdx: "fiteny malagasy",
  txy: "fiteny malagasy",
  xmw: "fiteny malagasy",
  ms: "Bahasa Melayu",
  msa: "Bahasa Melayu",
  may: "Bahasa Melayu",
  btj: "Bahasa Melayu",
  mfb: "Bahasa Melayu",
  bjn: "Bahasa Melayu",
  bve: "Bahasa Melayu",
  kxd: "Bahasa Melayu (Brunei)",
  bvu: "Bahasa Melayu",
  pse: "Bahasa Melayu",
  coa: "Bahasa Melayu",
  liw: "Bahasa Melayu",
  dup: "Bahasa Melayu",
  hji: "Bahasa Melayu",
  jak: "Bahasa Melayu",
  jax: "Bahasa Melayu",
  vkk: "Bahasa Melayu",
  meo: "Bahasa Melayu",
  kvr: "Bahasa Melayu",
  mqg: "Bahasa Melayu",
  kvb: "Bahasa Melayu",
  lce: "Bahasa Melayu",
  lcf: "Bahasa Melayu",
  zlm: "Bahasa Melayu",
  xmm: "Bahasa Melayu",
  min: "Bahasa Melayu",
  mui: "Bahasa Melayu",
  zmi: "Bahasa Melayu",
  max: "Bahasa Melayu",
  orn: "Bahasa Melayu",
  ors: "Bahasa Melayu",
  mfa: "Bahasa Melayu",
  pel: "Bahasa Melayu",
  msi: "Bahasa Melayu",
  zsm: "Bahasa Melayu (Malaysia)",
  tmw: "Bahasa Melayu",
  vkt: "Bahasa Melayu",
  urk: "Bahasa Melayu",
  mssg: "Bahasa Melayu (Singapura)",
  ml: "മലയാളം",
  mal: "മലയാളം",
  mt: "Malti",
  mlt: "Malti",
  mi: "te reo Māori",
  mri: "te reo Māori",
  mao: "te reo Māori",
  mr: "मराठी",
  mar: "मराठी",
  mh: "Kajin M̧ajeļ",
  mah: "Kajin M̧ajeļ",
  mn: "Монгол хэл",
  mon: "Монгол хэл",
  khk: "Монгол хэл",
  mfv: "Монгол хэл",
  na: "Dorerin Naoero",
  nau: "Dorerin Naoero",
  nv: "Diné bizaad",
  nav: "Diné bizaad",
  nd: "isiNdebele",
  nde: "isiNdebele",
  ne: "नेपाली",
  nep: "नेपाली",
  dty: "नेपाली",
  npi: "नेपाली",
  ng: "Owambo",
  ndo: "Owambo",
  nb: "Norsk Bokmål",
  nob: "Norsk Bokmål",
  nn: "Norsk Nynorsk",
  nno: "Norsk Nynorsk",
  no: "Norsk",
  nor: "Norsk",
  ii: "ꆈꌠ꒿ Nuosuhxop",
  iii: "ꆈꌠ꒿ Nuosuhxop",
  nr: "isiNdebele",
  nbl: "isiNdebele",
  oc: "occitan",
  oci: "occitan",
  oj: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  oji: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ciw: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ojb: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ojc: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ojg: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ojs: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  ojw: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  otw: "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  cu: "ѩзыкъ словѣньскъ",
  chu: "ѩзыкъ словѣньскъ",
  om: "Afaan Oromoo",
  orm: "Afaan Oromoo",
  gax: "Afaan Oromoo",
  hae: "Afaan Oromoo",
  orc: "Afaan Oromoo",
  gaz: "Afaan Oromoo",
  or: "ଓଡ଼ିଆ",
  ori: "ଓଡ଼ିଆ",
  ory: "ଓଡ଼ିଆ",
  spv: "ଓଡ଼ିଆ",
  os: "ирон æвзаг",
  oss: "ирон æвзаг",
  pa: "ਪੰਜਾਬੀ",
  pan: "ਪੰਜਾਬੀ",
  pi: "पालि",
  pli: "पालि",
  fa: "فارسی",
  fas: "فارسی",
  per: "فارسی",
  prs: "فارسی",
  pes: "فارسی",
  pl: "język polski",
  pol: "język polski",
  ps: "پښتو",
  pus: "پښتو",
  pst: "پښتو",
  pbu: "پښتو",
  pbt: "پښتو",
  pt: "Português",
  por: "Português",
  qu: "Runa Simi",
  que: "Runa Simi",
  qva: "Runa Simi",
  qxu: "Runa Simi",
  quy: "Runa Simi",
  qvc: "Runa Simi",
  qvl: "Runa Simi",
  qud: "Runa Simi",
  qxr: "Runa Simi",
  quk: "Runa Simi",
  qug: "Runa Simi",
  qxc: "Runa Simi",
  qxa: "Runa Simi",
  qwc: "Runa Simi",
  qwa: "Runa Simi",
  quz: "Runa Simi",
  qve: "Runa Simi",
  qub: "Runa Simi",
  qvh: "Runa Simi",
  qwh: "Runa Simi",
  qvw: "Runa Simi",
  qvi: "Runa Simi",
  qxw: "Runa Simi",
  quf: "Runa Simi",
  qvj: "Runa Simi",
  qvm: "Runa Simi",
  qvo: "Runa Simi",
  qul: "Runa Simi",
  qvn: "Runa Simi",
  qxn: "Runa Simi",
  qvz: "Runa Simi",
  qvp: "Runa Simi",
  qxh: "Runa Simi",
  qxp: "Runa Simi",
  qxl: "Runa Simi",
  qvs: "Runa Simi",
  qxt: "Runa Simi",
  qus: "Runa Simi",
  qws: "Runa Simi",
  quh: "Runa Simi",
  qxo: "Runa Simi",
  qup: "Runa Simi",
  quw: "Runa Simi",
  qur: "Runa Simi",
  qux: "Runa Simi",
  rm: "Rumantsch Grischun",
  roh: "Rumantsch Grischun",
  rn: "Ikirundi",
  run: "Ikirundi",
  ro: "Română",
  ron: "Română",
  rum: "Română",
  ru: "русский",
  rus: "русский",
  sa: "संस्कृतम्",
  san: "संस्कृतम्",
  sc: "sardu",
  srd: "sardu",
  sro: "sardu",
  sdn: "sardu",
  src: "sardu",
  sdc: "sardu",
  sd: "सिन्धी",
  snd: "सिन्धी",
  se: "Davvisámegiella",
  sme: "Davvisámegiella",
  sm: "gagana fa'a Samoa",
  smo: "gagana fa'a Samoa",
  sg: "yângâ tî sängö",
  sag: "yângâ tî sängö",
  sr: "српски језик",
  srp: "српски језик",
  gd: "Gàidhlig",
  gla: "Gàidhlig",
  sn: "chiShona",
  sna: "chiShona",
  si: "සිංහල",
  sin: "සිංහල",
  sk: "Slovenčina",
  slk: "Slovenčina",
  slo: "Slovenčina",
  sl: "Slovenski Jezik",
  slv: "Slovenski Jezik",
  so: "Soomaaliga",
  som: "Soomaaliga",
  st: "Sesotho",
  sot: "Sesotho",
  es: "Español",
  spa: "Español",
  su: "Basa Sunda",
  sun: "Basa Sunda",
  sw: "Kiswahili",
  swa: "Kiswahili",
  swc: "Kiswahili",
  swh: "Kiswahili",
  ss: "SiSwati",
  ssw: "SiSwati",
  sv: "Svenska",
  swe: "Svenska",
  ta: "தமிழ்",
  tam: "தமிழ்",
  te: "తెలుగు",
  tel: "తెలుగు",
  tg: "тоҷикӣ",
  tgk: "тоҷикӣ",
  th: "ไทย",
  tha: "ไทย",
  ti: "ትግርኛ",
  tir: "ትግርኛ",
  bo: "བོད་ཡིག",
  bod: "བོད་ཡིག",
  tib: "བོད་ཡིག",
  tk: "Türkmen",
  tuk: "Türkmen",
  tl: "Wikang Tagalog",
  tgl: "Wikang Tagalog",
  tn: "Setswana",
  tsn: "Setswana",
  to: "Faka Tonga",
  ton: "Faka Tonga",
  tr: "Türkçe",
  tur: "Türkçe",
  ts: "Xitsonga",
  tso: "Xitsonga",
  tt: "татар теле",
  tat: "татар теле",
  tw: "Twi",
  twi: "Twi",
  ty: "Reo Tahiti",
  tah: "Reo Tahiti",
  ug: "ئۇيغۇرچە‎",
  uig: "ئۇيغۇرچە‎",
  uk: "Українська",
  ukr: "Українська",
  ur: "اردو",
  urd: "اردو",
  uz: "Oʻzbek",
  uzb: "Oʻzbek",
  uzn: "Oʻzbek",
  uzs: "Oʻzbek",
  ve: "Tshivenḓa",
  ven: "Tshivenḓa",
  vi: "Tiếng Việt",
  vie: "Tiếng Việt",
  vo: "Volapük",
  vol: "Volapük",
  wa: "Walon",
  wln: "Walon",
  cy: "Cymraeg",
  cym: "Cymraeg",
  wel: "Cymraeg",
  wo: "Wollof",
  wol: "Wollof",
  fy: "Frysk",
  fry: "Frysk",
  xh: "isiXhosa",
  xho: "isiXhosa",
  yi: "ייִדיש",
  yid: "ייִדיש",
  ydd: "ייִדיש",
  yih: "ייִדיש",
  yo: "Yorùbá",
  yor: "Yorùbá",
  za: "Saɯ cueŋƅ",
  zha: "Saɯ cueŋƅ",
  zch: "Saɯ cueŋƅ",
  zhd: "Saɯ cueŋƅ",
  zeh: "Saɯ cueŋƅ",
  zgb: "Saɯ cueŋƅ",
  zgn: "Saɯ cueŋƅ",
  zln: "Saɯ cueŋƅ",
  zlj: "Saɯ cueŋƅ",
  zlq: "Saɯ cueŋƅ",
  zgm: "Saɯ cueŋƅ",
  zhn: "Saɯ cueŋƅ",
  zqe: "Saɯ cueŋƅ",
  zyg: "Saɯ cueŋƅ",
  zyb: "Saɯ cueŋƅ",
  zyn: "Saɯ cueŋƅ",
  zyj: "Saɯ cueŋƅ",
  zzj: "Saɯ cueŋƅ",
  zu: "isiZulu",
  zul: "isiZulu",
};
